<div class="top-static-menu">

<?php
//echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-static-menu')->toHtml();

?>
    <li>
        <a href="/about.html">О Нас</a>
    </li>
    <li>
        <a href="/conatcts.html">Контакты</a>
    </li>
    <li>
        <a href="/help.html">Помощь</a>
    </li>
    <li>
        <a href="/credit.html">Кредит</a>
    </li>
    <li>
        <a href="/rassrochka.html">Рассрочка</a>
    </li>
    <li>
        <a href="/payment.html">Оплата</a>
    </li>
    <li>
        <a href="/shipping.html">Доставка</a>
    </li>
    <li>
        <a href="/guarantee.html">Гарантия</a>
    </li>
    <li>
        <a href="/checkout/onepage/">Оформить заказ</a>
    </li>
    <li>
        <a href="/checkout/cart/">Корзина</a>
    </li>

</div>