<div class="top-middle-bar">
    <div class="top-middle-contacts">
        <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-phones')->toHtml(); ?>
        <ul class="top-contacts-phones">
            <li>
                <img class="top-contacts-phone-img" src="<?php echo $this->getSkinUrl('images/rozetka/header/life.jpg'); ?>" />
                <span>093-02-95-444</span>
            </li>
            <li>
                <img class="top-contacts-phone-img" src="<?php echo $this->getSkinUrl('images/rozetka/header/ks.jpg'); ?>" />
                <span>098-05-95-444</span>
            </li>


            </ul>
            <ul class="top-contacts-phones">
                <li>
                    <img class="top-contacts-phone-img" src="<?php echo $this->getSkinUrl('images/rozetka/header/mts.jpg'); ?>" />
                    <span>066-07-95-444</span>
                </li>
                <li>
                    <img class="top-contacts-phone-img" src="<?php echo $this->getSkinUrl('images/rozetka/header/mts.jpg'); ?>" />
                    <span>066-50-95-444</span>
                </li>
             </ul>

            <ul>
            <li style="float:right">
                <span>
                    <a href="/contacts/">
                        Заказать звонок
                    </a>
                </span>
            </li>
            <li style="float:right">
                <span>
                    <a href="/contacts/">
                        Обратная связь
                    </a>
                </span>
                |&nbsp;
            </li>
            <li style="float:right">
                <span>
                    <a href="/contact/account/">
                        Личный кабинет
                    </a>
                </span>
                |&nbsp;
            </li>
        </ul>
    </div>
    <div class="top-middle-info">
        <div><a href="<?php echo $this->getBaseUrl() ?>">ROZETKA.CO.UA</a></div>
        <div>
            Интернет магазин "Все для тебя"
        </div>
    </div>

</div>